[project]
name = "SR_project"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pyyaml",
    "toml"
]

[tool.uv]
# Optional: Configure `uv` settings (not for dependencies)

[tool.ruff]
line-length = 88
select = ["ALL"]
